### ISSUE TITLE
Error running EDS

### ISSUE THREAD

**Issue by franciscoRdiaz** [elastest/elastest-device-emulator-service#74]
Hi,

I am trying to run EDS inside a docker-machine (boot2docker) and when I execute the `startup-linux.sh`, the result is the following error:

ERROR: for memsipe  Cannot start service memsipe: linux runtime spec devices: error gathering device information while adding custom device "/dev/i2c-1": lstat /dev/i2c-1: no such file or directory
			ERROR: Encountered errors while bringing up the project.

Regards.

**Comment by varungowtham** [comment]
Hi, 
MemsIPE uses smbus2 python module to access a device node called "/dev/i2c-1". In the docker compose, the host's device node is mapped to the memsipe container, therefore it is expected that the host provides i2c-1 device node. This has been mentioned in How to run section of documentation. 

Solution: please make i2c-1 device node available on the host machine by following below mentioned steps:
1. locate major number of i2c device driver by executing 
`cat /proc/devices`
2. create the required i2c-1 device node, assuming 89 is the major number of i2c driver.
`sudo mknod /dev/i2c-1 c 89 0`

I hope this solves the issue. Please feel free to comment if you have any other issue. 

Best regards, 
Varun
